### ISSUE TITLE
Pixhawk ESC 1.6 does not boot up properly when fw flashed with CAN adapter

### ISSUE THREAD

**Issue by CarlOlsson** [thiemar/vectorcontrol#11]
We are able to flash the vectorcontrol fw to the SV2470VC with the USB-CAN adapter from Ben without problems but when doing the same to the Pixhawk 1.6 ESC it does not work. The ESC keep reinitializing 
and does not spin or give feedback.

However, when flashing the fw to the Pixhawk 1.6 ESC it works. (Except for the performance issues #12 )

**Comment by bendyer** [comment]
I am unable to reproduce this issue—I use the CAN adapter exclusively during development and firmware always loads fine. What application firmware image did you load when you observed the restarting behaviour?

**Comment by CarlOlsson** [comment]
The issue is present on all fw:s (e.g. 544c8_gcc4_8_3_sverling) that get passed the flashing stage, i.e. #14

**Comment by bendyer** [comment]
Please could you send through a log of the process from starting `ui.py` through to after the ESC has restarted a few times?

**Comment by CarlOlsson** [comment]
After updating the gui hash: **68e34de6** we are able to flash the fw in 68e34de6_gcc4_8_4_Ben to the Pixhawk ESC 1.6 with the CAN-Adapter

**Comment by boosfelm** [comment]
thanks for fixing @bendyer and verifying @CarlOlsson !
