### ISSUE TITLE
One particular S2740VC consumes 550mA at 12V after initialization

### ISSUE THREAD

**Issue by boosfelm** [thiemar/vectorcontrol#13]
One of our S2740VC consumes 40mA during initialization (normal), then 550mA at 12V.
We erased chip, same bootloader, same fw as another hw which is working. Probably hw failure due to boot up with wrong fw. Do you agree?

**Comment by bendyer** [comment]
Yes, definitely hardware failure. I think the cause is most likely to be firmware for the wrong ESC being loaded, but at this point it's probably not possible to determine.
